version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.5
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./data_mosquitto/data:/mosquitto/data
      - ./data_mosquitto/log:/mosquitto/log
    restart: always
  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./data_influxdb:/var/lib/influxdb
    restart: always
  telegraf:
      image: telegraf
      container_name: telegraf
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      restart: always
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ./data_grafana:/var/lib/grafana
    restart: always
  cam_receiver:
    build: ./cam_receiver
    image: damok6/cam_receiver
    container_name: cam_receiver
    ports:
      - 21000:21000
      - 21001-21010:21001-21010
    environment:
      - MQTT_HOST=mosquitto
      - PASSIVE_PORT_RANGE=21001-21010
    depends_on:
      - mosquitto
      - influxdb
    restart: always
